[env]
RUST_BACKTRACE = "1"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.install-nightly]
command = "rustup"
args = ["toolchain", "install", "nightly", "--component", "rustfmt"]

[tasks.install-fmt]
command = "rustup"
args = ["component", "add", "rustfmt", "--toolchain", "nightly"]
dependencies = ["install-nightly"]

[tasks.fmt]
toolchain = "nightly"
command = "cargo"
args = ["fmt"]
dependencies = ["install-fmt"]

[tasks.test]
command = "cargo"
args = ["--locked", "test", "--", "--quiet", "--show-output"]

[tasks.tdd]
install_crate = "cargo-watch"
command = "cargo"
args = [ "watch"
       , "--watch", "./src"
       , "--watch", "./tests"
       , "--delay", "0"
       , "-x", "make -t test"
       ]

[tasks.fmt-check]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--", "--check"]
dependencies = ["install-fmt"]

[tasks.clippy-check]
command = "cargo"
args = ["clippy"]

[tasks.ci]
dependencies = ["test", "fmt-check", "clippy-check"]

[tasks.update-readme]
script = "cargo install cargo-readme && cargo readme > README.md"
