[env]
RUST_BACKTRACE = "1"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.install-nightly]
command = "rustup"
args = ["toolchain", "install", "nightly", "--component", "rustfmt"]

[tasks.install-fmt]
command = "rustup"
args = ["component", "add", "rustfmt", "--toolchain", "nightly"]
dependencies = ["install-nightly"]

[tasks.fmt]
toolchain = "nightly"
command = "cargo"
args = ["fmt"]
dependencies = ["install-fmt"]

[tasks.test]
command = "cargo"
args = ["--locked", "test", "--", "--quiet", "--show-output"]

[tasks.test-quiet]
command = "cargo"
args = ["--quiet", "--locked", "test"]

[tasks.fmt-check]
toolchain = "nightly"
command = "cargo"
args = ["--quiet", "fmt", "--", "--check", "--quiet"]
dependencies = ["install-fmt"]

[tasks.clippy-check]
command = "cargo"
args = ["--quiet", "clippy"]

[tasks.doc-check]
command = "cargo"
args = ["--quiet", "doc"]

[tasks.ci]
dependencies = ["test-quiet", "fmt-check", "clippy-check", "doc-check"]

[tasks.update-readme]
script = "cargo install cargo-readme && cargo readme > README.md"
