extend = "../Makefile.toml"

[tasks.check-no-std]
command = "cargo"
args = ["check", "--no-default-features"]

[tasks.check-alloc]
command = "cargo"
args = ["check", "--no-default-features", "--features", "alloc"]

[tasks.ci]
dependencies = ["test", "fmt-check", "clippy-check", "check-no-std", "check-alloc"]
