extend = "../Makefile.toml"

[tasks.bench]
install_crate = "cargo-criterion"
command = "cargo"
args = ["criterion"]

[tasks.flame]
install_crate = "cargo-flamegraph"
command = "cargo"
args = ["flamegraph", "--bench", "profile", "--", "--bench"]

[tasks.check-no-std]
command = "cargo"
args = ["check", "--no-default-features"]

[tasks.check-alloc]
command = "cargo"
args = ["check", "--no-default-features", "--features", "alloc"]

[tasks.ci]
dependencies = ["test", "fmt-check", "clippy-check", "check-no-std", "check-alloc"]

[tasks.tdd]
install_crate = "cargo-watch"
command = "cargo"
args = [ "watch"
       , "--clear"
       , "--watch", "kwap-TODO/src"
       , "--delay", "0"
       , "-x", "make --cwd kwap-TODO -t test-quiet --loglevel error"
       ]
