name: 'bump'

on:
  push:
    branches: [ 'main' ]

jobs:
  bump:
    if: |
         !startsWith(github.event.head_commit.message, 'bump')
         && !startsWith(github.event.head_commit.message, 'ci')
         && !startsWith(github.event.head_commit.message, 'chore')
         && !startsWith(github.event.head_commit.message, '[NO_PUB]')
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'
      with:
        token: ${{ secrets.GH_TOKEN }}

    - run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo

    - uses: 'actions/setup-node@v1'
      with: { node-version: '14' }

    - uses: dorny/paths-filter@v2
      id: package_changed
      with:
        filters: |
          kwap-msg: ['kwap_msg/**']
          kwap-macros: ['kwap_macros/**']
          kwap-common: ['kwap_common/**']
          kwap: ['kwap/**']

    # running `standard-version` will:
    # - update CHANGELOG,
    # - create version tag
    # - create version commits

    - name: 'bump kwap-msg'
      if: steps.package_changed.outputs.kwap-msg == 'true'
      run: |
        npx standard-version \
          --tag-prefix kwap-msg@ \
          --releaseCommitMessageFormat 'chore(release): kwap-msg@{{currentTag}}'
      working-directory: 'kwap_msg'

    - name: 'bump kwap-macros'
      if: steps.package_changed.outputs.kwap-macros == 'true'
      run: |
        npx standard-version \
          --tag-prefix kwap-macros@ \
          --releaseCommitMessageFormat 'chore(release): kwap-macros@{{currentTag}}'
      working-directory: 'kwap_macros'

    - name: 'bump kwap'
      if: steps.package_changed.outputs.kwap == 'true'
      run: |
        npx standard-version \
          --tag-prefix kwap@ \
          --releaseCommitMessageFormat 'chore(release): kwap@{{currentTag}}'
      working-directory: 'kwap'

    - name: 'bump kwap-common'
      if: steps.package_changed.outputs.kwap-common == 'true'
      run: |
        npx standard-version \
          --tag-prefix kwap-common@ \
          --releaseCommitMessageFormat 'chore(release): kwap-common@{{currentTag}}'
      working-directory: 'kwap_common'

    - name: 'update Cargo.lock'
      run: 'cargo check'

    - run: |
        git add -A
        git commit --amend --no-edit

    - env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: 'git push'

    # publish will be triggered by new tags
    - env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: 'git push --tags'
