name: 'ci check'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  ci_check:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup/toolchains
          ~/.cargo/bin
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: rust-${{ runner.os }}

    - uses: dorny/paths-filter@v2
      id: package_changed
      with:
        filters: |
          toad-msg: ['toad-msg/**']
          toad-macros: ['toad-macros/**']
          toad-common: ['toad-common/**']
          toad: ['toad/**']

    - run: |
        if [ ! -f ~/.cargo/bin/cargo-make ];
        then
          cargo install cargo-make
        else
          echo 'cargo-make already available.'
        fi

    - name: 'check toad-msg'
      run: 'cargo make ci'
      if: github.ref == 'refs/heads/main' || steps.package_changed.outputs.toad-msg == 'true'
      working-directory: 'toad-msg'

    - name: 'check toad-common'
      run: 'cargo make ci'
      if: github.ref == 'refs/heads/main' || steps.package_changed.outputs.toad-common == 'true'
      working-directory: 'toad-common'

    - name: 'check toad-macros'
      run: 'cargo make ci'
      if: github.ref == 'refs/heads/main' || steps.package_changed.outputs.toad-macros == 'true'
      working-directory: 'toad-macros'

    - name: 'check toad'
      run: 'cargo make ci'
      if: github.ref == 'refs/heads/main' || steps.package_changed.outputs.toad == 'true'
      working-directory: 'toad'

    - name: 'check toad-writable'
      run: 'cargo make ci'
      if: github.ref == 'refs/heads/main' || steps.package_changed.outputs.toad-writable == 'true'
      working-directory: 'toad-writable'

    - name: 'check toad-array'
      run: 'cargo make ci'
      if: github.ref == 'refs/heads/main' || steps.package_changed.outputs.toad-array== 'true'
      working-directory: 'toad-array'

    - name: 'check toad-len'
      run: 'cargo make ci'
      if: github.ref == 'refs/heads/main' || steps.package_changed.outputs.toad-len== 'true'
      working-directory: 'toad-len'

    - name: 'check toad-hash'
      run: 'cargo make ci'
      if: github.ref == 'refs/heads/main' || steps.package_changed.outputs.toad-hash== 'true'
      working-directory: 'toad-hash'

    - name: 'check toad-stem'
      run: 'cargo make ci'
      if: github.ref == 'refs/heads/main' || steps.package_changed.outputs.toad-stem== 'true'
      working-directory: 'toad-stem'

    - name: 'check toad-cursor'
      run: 'cargo make ci'
      if: github.ref == 'refs/heads/main' || steps.package_changed.outputs.toad-cursor== 'true'
      working-directory: 'toad-cursor'

    - name: 'check toad-map'
      run: 'cargo make ci'
      if: github.ref == 'refs/heads/main' || steps.package_changed.outputs.toad-map== 'true'
      working-directory: 'toad-map'
