name: 'publish'

on:
  push:
    tags: ['*']

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo

    - name: 'publish kwap-msg'
      if: startsWith(github.ref, 'refs/tags/kwap-msg@')
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: 'cargo publish'
      working-directory: 'kwap_msg'

    - name: 'publish kwap-macros'
      if: startsWith(github.ref, 'refs/tags/kwap-macros@')
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: 'cargo publish'
      working-directory: 'kwap_macros'

    - name: 'publish kwap'
      if: startsWith(github.ref, 'refs/tags/kwap@')
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: 'cargo publish'
      working-directory: 'kwap'

    - name: 'publish kwap-common'
      if: startsWith(github.ref, 'refs/tags/kwap-common@')
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: 'cargo publish'
      working-directory: 'kwap_common'
